language: python
python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  include:
  - python: 3.7
    dist: xenial
before_install:
- pip install poetry
install:
- poetry install --dev
before_script:
- flake8 flask_praetorian
- flake8 tests
script:
- poetry run pytest tests
before_deploy:
- poetry config http-basic.pypi dusktreader $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  on:
    tags: true
env:
  global:
    secure: bUjH7SW/nwwOY5H3JFiIlH0vXpcJ61L5PFOKw0j49UA0SSrCgei+PjcQSLwSW7jAkIHG0Di0sUqw4MMCPlENZz55G904qO/OR3p/k2csyqZoFvr+InGphxkJ+e+j7opRb31W/pn0BUJeveLjU6IBrm9PSxWUn0QohIbkipad9stdk9bjnihxiXLHWJhwtp47zu6quO8BSnO7LPRTA6QMvnms34NfJne0RhzdOSeEM4VTXx2A7NH1jCH2RdvBOfN35L43CLPh9UCAmIB+WGHHDsbZwRNVf2+kUatMVRENSxFr0petEaIfOfxYiQ4kH4g1Fi+IS+1RKECcnzm9ngMMk8IJLe1vUGbICdz3iQQ24knhW31rWm1PQipm18SwbGC5WrkHJNTgzDmn5kJTbxwQOVHJf7ZsnNyF9Wtevm18GFeCX/E1Qi0bVxnmBpSsjqrGaBLBSQ8Fxp9+fukJ0dZTMnndJf7qdcUs9kkVilgcbvM3B+UW00S4AMZMVHNNtqJGeOvo2DFA5f2aMGNvIxCmdLQ5pJts+8ZeBJVQEj9kCs2l0helUYrswVVcsd22u0fFVHNDDdwsQyB+ZyhemHzIxb5KybUNTfBfsS6RVw9UlztdX4QAuXH6n+mMemDQJBqpNcYPhTVbIB+o4XXU/5GPWQLcBvoQ0/T4vFIcnv87XY8=
