language: python
python:
- '3.5'
- '3.6'
- '3.7-dev'
install:
- pip install --upgrade pip
- pip install .[dev]
before_script:
- flake8 flask_praetorian
- flake8 tests
script: py.test tests
deploy:
  provider: pypi
  user: dusktreader
  password:
    secure: i4SHf79znFQPxW/MIbIUCpug47LbnkvW3BFlHTZWIy9En6LNAwjmaoVWBzCOiEQctAc+LYcB8qpK5dx31WMPZhwDN7Q3R+L914you6O+sgmAKpZQI5+eG6g1dCt56u+RlYhatws0NJCWD4IUYBdwW4xESDI6YZ5sBlCyh2fwlPQuykib50VbbOtQwGdNEzlJVZ7WwcdZ+oQMsr8M7ex4zpaaStFE3UufOmtXzi7vZ3LQoGCg9iG1fElL7YZXZgq/jpo9ZN2Is9RL50H1Tc+U9Rv6jYCz/T09V+F7I3Kypbp+DQRwrJdY1dc+agzjfl+YP85D7cnPu142G8fuugNt4lOORGPwbDrETB9A24ER7haq+yJqu+PV937v3V9lWswmbyTaHufNhAAQC73Yu9xZLIoc4ctB00Vxicj+NBMYucXHEakq5vQ88a91KKYSOj4yiwQGY72cZk2xZ5+wuSGdSZ7kPOXwsDs/OJ1c5/o60MLgRLrH/2XjUVLUQrxdVuQJfmMhVjnVA4M2s83G7McAZZsyehVV1Se/YGDz/Xcff4XLHSYIt7QB6PaX6sGH/nPTeQzuXr0DQQnneiTXWhrhuMdSXoVLGN/GTY02lgr15sk+TKb4nFyYcnh09BPYPYqp78Ou6LBPd+HN75c0s4v8f5jQp2ELpKX+W6+nUl8gcp0=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dusktreader/flask-praetorian
    python: 3.6
